---
title: "Exploratory Analysis"
output: html_document
---

## Project title

Give your project a concise, interesting title that summarizes the entirety of your project

### Authors

Names of your team members

### Date

Winter 2022

### Abstract

No more than three sentences that summarize your project. Focus on the very most important aspects. For example: (1) "Our main question is .... This question is important because .... To address the question, we will ...." (2) "We are concerned with ..., because .... To address this concern, we plan to ...." (3) "Consider that .... This is important because .... Accordingly, we plan to ...."

### Keywords

3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")

### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

The project's broader challenges involve potential data issues like missing values and outliers, which might impact analysis accuracy. The dataset's scope and coverage limitations, focusing on specific regions and omitting confounding variables like socioeconomic status, could affect generalizability. Establishing causation between alcohol consumption and life expectancy requires more rigorous study designs, and cultural variations may introduce biases. To address these challenges, thorough data cleaning, robust statistical methods, and diverse datasets are essential. Caution must be exercised in making causal claims without supporting evidence, acknowledging uncertainties in findings.


### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

The summary information reveals key statistics calculated from the dataset: minimum and maximum life expectancy, mean life expectancy by alcohol consumption amount, median, and ***. These values provide an overview of life expectancy distribution, offering insights into patterns and variability, but they should be interpreted with consideration for the dataset's limitations.

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

#``````{r, echo = FALSE, code = readLines("chart1_example.R")}
#```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

``````{r, echo = FALSE, code = readLines("chart3.R")}
```

Describe why you chose this chart and what information it reveals

I chose this line chart to visualize the relationship between alcohol consumption and life expectancy as it helps reveal trends or patterns between these variables, showing how life expectancy changes with varying alcohol consumption levels.
